### ISSUE TITLE
Create and document all components, groups, and templates in Figma v0.1

### ISSUE THREAD

**Issue by AlexJupiter** [DemocracyEarth/DesignSystem#3]
This is restricted to the first version of the dApp, meaning that the only template is the ballot dashboard page.

**Comment by AlexJupiter** [comment]
@agazima @marikio I believe that this issue can be closed now, what do you think?

Here is a video of the progress made in regards to this issue: https://drive.google.com/file/d/1CCidEAgr06TWB6bIRyRoZiI_aGErHNdA/view?usp=sharing

**Comment by AlexJupiter** [comment]
@marikio @agazima and thoughts on this? Can I close this?

**Comment by marikio** [comment]
@AlexJupiter Yep! I think so! Could we just change the name of the issue to include the version number?

**Comment by AlexJupiter** [comment]
@marikio Does v0.1 sound appropriate?

**Comment by marikio** [comment]
Yep!
